/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObrasRouteImport } from './routes/obras'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObrasIndexRouteImport } from './routes/obras.index'
import { Route as ObrasCategoryRouteImport } from './routes/obras.$category'

const ObrasRoute = ObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasIndexRoute = ObrasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ObrasRoute,
} as any)
const ObrasCategoryRoute = ObrasCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ObrasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/obras': typeof ObrasRouteWithChildren
  '/obras/$category': typeof ObrasCategoryRoute
  '/obras/': typeof ObrasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/obras/$category': typeof ObrasCategoryRoute
  '/obras': typeof ObrasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/obras': typeof ObrasRouteWithChildren
  '/obras/$category': typeof ObrasCategoryRoute
  '/obras/': typeof ObrasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contacto' | '/obras' | '/obras/$category' | '/obras/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contacto' | '/obras/$category' | '/obras'
  id: '__root__' | '/' | '/contacto' | '/obras' | '/obras/$category' | '/obras/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  ObrasRoute: typeof ObrasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/obras': {
      id: '/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof ObrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras/': {
      id: '/obras/'
      path: '/'
      fullPath: '/obras/'
      preLoaderRoute: typeof ObrasIndexRouteImport
      parentRoute: typeof ObrasRoute
    }
    '/obras/$category': {
      id: '/obras/$category'
      path: '/$category'
      fullPath: '/obras/$category'
      preLoaderRoute: typeof ObrasCategoryRouteImport
      parentRoute: typeof ObrasRoute
    }
  }
}

interface ObrasRouteChildren {
  ObrasCategoryRoute: typeof ObrasCategoryRoute
  ObrasIndexRoute: typeof ObrasIndexRoute
}

const ObrasRouteChildren: ObrasRouteChildren = {
  ObrasCategoryRoute: ObrasCategoryRoute,
  ObrasIndexRoute: ObrasIndexRoute,
}

const ObrasRouteWithChildren = ObrasRoute._addFileChildren(ObrasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  ObrasRoute: ObrasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
